# Generated by Django 4.1 on 2023-05-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignWord',
            fields=[
                ('sign_id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100, unique=True)),
                ('wordtype', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100)),
                ('photo_url', models.CharField(default=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'signword',
            },
        ),
    ]
