# Generated by Django 4.1 on 2023-05-08 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signlanguage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incorrect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sign_id', models.ForeignKey(db_column='sign_id', on_delete=django.db.models.deletion.CASCADE, related_name='incorrect', to='signlanguage.signword')),
            ],
            options={
                'db_table': 'incorrect',
            },
        ),
    ]
