# Generated by Django 4.1 on 2023-05-08 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incorrect_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorrect',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='incorrect', to=settings.AUTH_USER_MODEL),
        ),
    ]
